=== UweSchmidt/apps/test/config/archive.dtd
<?xml encoding="ISO-8859-1"?>
<!-- DTD for a simple web photo album -->

<!-- the root tag -->
<!ELEMENT archive	(config?, album)	>
<!ATTLIST archive	xmlns	CDATA	#FIXED	"http://muehle.welt.all/photos.dtd"
			base	CDATA	#IMPLIED
			config	CDATA	#IMPLIED	>

<!-- general info for various tags for a arbitrary key-value pairs -->
<!ELEMENT attr		ANY				>
<!ATTLIST attr		name	CDATA	#REQUIRED
			entity	CDATA  	#IMPLIED	>

<!-- a collection of pictures and sub albums -->
<!ELEMENT album		(error*, orig?, copy*, attr*, (album | picture)*)	>
<!ATTLIST album		id	NMTOKEN	#REQUIRED
			entity	CDATA  	#IMPLIED
			extern	NMTOKEN	#IMPLIED
			base	CDATA	#IMPLIED
			baseref	CDATA	#IMPLIED
			href	CDATA	#IMPLIED	>

<!-- description of a single picture -->
<!ELEMENT picture	(error*, orig?, copy*, attr*)	>
<!ATTLIST picture	id	NMTOKEN	#REQUIRED
			entity	CDATA  	#IMPLIED
			base	CDATA	#IMPLIED
			baseref	CDATA	#IMPLIED
			href	CDATA	#IMPLIED	>

<!-- the original source of pictures -->
<!ELEMENT orig		EMPTY				>
<!ATTLIST orig		href	CDATA	#IMPLIED
			raw	CDATA	#IMPLIED
			href1	CDATA	#IMPLIED
			raw1	CDATA	#IMPLIED
			rotate	CDATA	#IMPLIED
			gamma	CDATA	#IMPLIED	>

<!-- the data about a resized copy of a picture -->
<!ELEMENT copy		EMPTY				>
<!ATTLIST copy		href	CDATA	#IMPLIED
			base	CDATA	#IMPLIED
			geometry CDATA	#IMPLIED	>

<!-- error messages when processing image or file -->
<!ELEMENT error		ANY				>

<!-- representation configuration data -->
<!ELEMENT config	(attr*, picture-attributes?, layout*, dictionary*, size*)		>
<!ATTLIST config	entity	CDATA  	#IMPLIED
			config	CDATA	#IMPLIED	>

<!ELEMENT picture-attributes	(attr*)			>

<!-- layout information about a specific layout -->
<!ELEMENT layout	(attr*, page*)			>
<!ATTLIST layout	id	NMTOKEN	#REQUIRED
			type	CDATA	#REQUIRED
			entity	CDATA  	#IMPLIED
			config	CDATA	#IMPLIED	>

<!-- dictionary for language translation layout -->
<!ELEMENT dictionary	(attr*)			>
<!ATTLIST dictionary	id	NMTOKEN	#REQUIRED	>

<!-- layout info about album or picture pages -->
<!ELEMENT page		(attr*)				>
<!ATTLIST page		type	( picture
				| album
				)	#REQUIRED
			entity	CDATA  	#IMPLIED
			config	CDATA	#IMPLIED	>

<!ELEMENT a		ANY				>
<!ATTLIST a		href	CDATA	#REQUIRED
                        title   CDATA   #IMPLIED
			target	CDATA  	#IMPLIED	>

<!-- size info for picture copies to be generated -->
<!ELEMENT size		(attr*)				>

<!-- include ISO Latin 1 xhtml entities -->
<!ENTITY % HTMLlat1 PUBLIC
       "-//W3C//ENTITIES Latin 1 for XHTML//EN"
       "xhtml-lat1.ent">
%HTMLlat1;

=== UweSchmidt/apps/photo2/test/config/archive2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "archive.dtd">
<config>
  <attr name="album-dir">album2</attr>
  <attr name="base">../Diakaesten</attr>
  <attr name="copy-copy">0</attr>
  <attr name="copy-exif">0</attr>
  <attr name="debug">1</attr>
  <attr name="dir">org</attr>
  <attr name="dtd">config/archive.dtd</attr>
  <attr name="imgtype">jpg</attr>
  <attr name="import-base">../Diakaesten</attr>
  <attr name="import-dialog">0</attr>
  <attr name="import-dir">2007/2007.03.11.Hagenbeck/uwe2</attr>
  <attr name="import-pattern">.*</attr>
  <attr name="import-since">1970-01-01</attr>
  <attr name="layout">html-1400x1050</attr>
  <attr name="layout-icon">160x120</attr>
  <attr name="layout-image">1600x1200</attr>
  <attr name="store-format">picture</attr>
  <picture-attributes>
    <attr name="cam:CameraModelName">(.*:)?CameraModelName|model</attr>
    <attr name="cam:FocalLength">(.*:)?FocalLength</attr>
    <attr name="cam:FocalLengthIn35mmFormat">(.*:)?FocalLengthIn35mmFormat</attr>
    <attr name="cam:Lens">(.*:)?[Ll]ens</attr>
    <attr name="cam:LensID">(.*:)?[Ll]ensID|lens-id</attr>
    <attr name="cam:LensSpec">(.*:)?[Ll]ensSpec|lens-spec</attr>
    <attr name="cam:Make">(.*:)?Make|manufacturer</attr>
    <attr name="descr:Comment">(.*:)?[Cc]omment</attr>
    <attr name="descr:GeoCode">(.*:)?[Gg]eo[Cc]ode</attr>
    <attr name="descr:GoogleMaps">(.*:)?[Gg]oogle[Mm]aps</attr>
    <attr name="descr:Keywords">(.*:)?[Kk]eywords</attr>
    <attr name="descr:Resource">(.*:)?[Rr]esource</attr>
    <attr name="descr:Location">(.*:)?[Ll]ocation</attr>
    <attr name="descr:Subject">(.*:)?[Ss]ubject</attr>
    <attr name="descr:Subtitle">(.*:)?[Ss]ub[Tt]itle</attr>
    <attr name="descr:Title">(.*:)?[Tt]itle</attr>
    <attr name="descr:TitleEnglish">(.*:)?[Tt]itle[Ee]nglish</attr>
    <attr name="descr:TitleLatin">(.*:)?[Tt]itle[Ll]atin</attr>
    <attr name="descr:UserComment">(.*:)?UserComment|user-comment</attr>
    <attr name="descr:Web">(.*:)?[Ww]eb</attr>
    <attr name="descr:Wikipedia">(.*:)?[Ww]ikipedia</attr>
    <attr name="exif:Aperture">(.*:)?Aperture</attr>
    <attr name="exif:ColorSpaceData">(.*:)?ColorSpaceData|color-space</attr>
    <attr name="exif:Contrast">(.*:)?[Cc]ontrast</attr>
    <attr name="exif:CreateDate">(.*:)?CreateDate|date-and-time</attr>
    <attr name="exif:DateTimeOriginal">(.*:)?DateTimeOriginal|date-and-time-original</attr>
    <attr name="exif:DepthOfField">(.*:)?[Dd]epth[oO]f[Ff]ield|depth-of-field</attr>
    <attr name="exif:ExposureCompensation">(.*:)?ExposureCompensation|exposure-bias|exposure-compensation</attr>
    <attr name="exif:ExposureMode">(.*:)?ExposureMode|exposure-mode</attr>
    <attr name="exif:ExposureProgram">(.*:)?ExposureProgram|exposure-program</attr>
    <attr name="exif:ExposureTime">(.*:)?ExposureTime|exposure-time</attr>
    <attr name="exif:Flash">(.*:)?[Ff]lash</attr>
    <attr name="exif:FlashSetting">(.*:)?[Ff]lash-?[Ss]etting</attr>
    <attr name="exif:FNumber">(.*:)?FNumber|fnumber</attr>
    <attr name="exif:FocalLength">(.*:)?FocalLength|focal-length</attr>
    <attr name="exif:FocalLengthIn35mmFormat">(.*:)?FocalLengthIn35mmFormat|focal-length-in-35mm</attr>
    <attr name="exif:FocusDistance">(.*:)?FocusDistance|focus-distance</attr>
    <attr name="exif:FocusMode">(.*:)?FocusMode|focus-mode</attr>
    <attr name="exif:ImageSize">(.*:)?ImageSize|geometry</attr>
    <attr name="exif:ISO">(.*:)?ISO|iso-setting</attr>
    <attr name="exif:MeteringMode">(.*:)?MeteringMode|metering-mode</attr>
    <attr name="exif:Quality">(.*:)?[Qq]uality</attr>
    <attr name="exif:Saturation">(.*:)?[Ss]aturation</attr>
    <attr name="exif:Sharpness">(.*:)?[Ss]harpness</attr>
    <attr name="exif:ShootingMode">(.*:)?ShootingMode|shooting-mode</attr>
    <attr name="exif:ShutterSpeed">(.*:)?ShutterSpeed|shutter-speed</attr>
    <attr name="exif:VibrationReduction">(.*:)?VibrationReduction|vibration-reduction</attr>
    <attr name="exif:WhiteBalance">(.*:)?WhiteBalance|white-balance</attr>
    <attr name="file:FileModificationDateTime">(.*:)?FileModificationDateTime|modified</attr>
    <attr name="file:FileSize">(.*:)?FileSize|file-size</attr>
    <attr name="file:RefOrig">(.*:)?RefOrig|ref-org</attr>
    <attr name="file:RefRaw">(.*:)?RefRaw|ref-raw</attr>
    <attr name="file:RefXmp">(.*:)?RefXmp|ref-xmp</attr>
    <attr name="show:Duration">(.*:)?[Dd]uration</attr>
  </picture-attributes>
  <layout id="html-1024x768" type="html-css2">
    <page type="album">
      <attr name="template">config/html-1024x768-album-template.xml</attr>
    </page>
    <page type="picture">
      <attr name="template">config/html-1024x768-picture-template.xml</attr>
    </page>
  </layout>
  <layout id="html-1400x1050" type="html-css2">
    <page type="album">
      <attr name="template">config/html-1400x1050-album-template.xml</attr>
    </page>
    <page type="picture">
      <attr name="template">config/html-1400x1050-picture-template.xml</attr>
    </page>
  </layout>
  <layout id="html-1600x1200" type="html-css2">
    <page type="album">
      <attr name="template">config/html-1600x1200-album-template.xml</attr>
    </page>
    <page type="picture">
      <attr name="template">config/html-1600x1200-picture-template.xml</attr>
    </page>
  </layout>
  <dictionary id="exif-german">
    <attr name="Aperture-priority">Blendenvorwahl</attr>
    <attr name="As Shot">Wie aufgenommen</attr>
    <attr name="Auto">Automatik</attr>
    <attr name="Center-weighted average">Mittenzentriert</attr>
    <attr name="Center-weighted averaging">Mittenzentriert</attr>
    <attr name="Cloudy">Bew√∂lkt</attr>
    <attr name="Continuous">Serie</attr>
    <attr name="Custom">"Benutzerdefiniert</attr>
    <attr name="Daylight">Tageslicht</attr>
    <attr name="Evaluative">bewertend</attr>
    <attr name="Exposure Bracketing">Belichtungsreihe</attr>
    <attr name="Fine">Hoch</attr>
    <attr name="Fired">Blitz</attr>
    <attr name="Manual">Manuell</attr>
    <attr name="Mode">Modus</attr>
    <attr name="Multi-segment">Multi-Segment</attr>
    <attr name="No Flash">Ohne Blitz</attr>
    <attr name="None">Nichts</attr>
    <attr name="Off">Aus</attr>
    <attr name="On">Ein</attr>
    <attr name="Single">Einzelbild</attr>
    <attr name="Single-Frame">Einzelbild</attr>
    <attr name="Spot">Punktmessung</attr>
    <attr name="Superfine">Extra hoch</attr>
    <attr name="Unknown">Nicht bekannt</attr>
  </dictionary>
  <size>
    <attr name="dir">1600x1200</attr>
    <attr name="geometry">1600x1200</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">1400x1050</attr>
    <attr name="geometry">1400x1050</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">1024x768</attr>
    <attr name="geometry">1024x768</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">160x120</attr>
    <attr name="geometry">160x120</attr>
    <attr name="aspect-ratio">fix</attr>
  </size>
  <size>
    <attr name="dir">100x75</attr>
    <attr name="geometry">100x75</attr>
    <attr name="aspect-ratio">fix</attr>
  </size>
  <size>
    <attr name="dir">100x100</attr>
    <attr name="geometry">100x100</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">160x120-photoEdit</attr>
    <attr name="geometry">160x120</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
</config>

=== UweSchmidt/apps/photo2/test/config/archive.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE config SYSTEM "archive.dtd">
<config>
  <attr name="album-dir">album2</attr>
  <attr name="base">../Diakaesten</attr>
  <attr name="debug">1</attr>
  <attr name="dir">org</attr>
  <attr name="dtd">config/archive.dtd</attr>
  <attr name="entities">archive</attr>
  <attr name="imgtype">jpg</attr>
  <attr name="import-base">../Diakaesten</attr>
  <attr name="import-pattern">.*/uwe2/.*</attr>
  <attr name="import-since">2007</attr>
  <attr name="layout">html-1600x1200</attr>
  <attr name="store-all">1</attr>
  <picture-attributes>
    <attr name="cam:CameraModelName">(.*:)?CameraModelName|model</attr>
    <attr name="cam:FocalLength">(.*:)?FocalLength</attr>
    <attr name="cam:FocalLengthIn35mmFormat">(.*:)?FocalLengthIn35mmFormat</attr>
    <attr name="cam:Lens">(.*:)?[Ll]ens</attr>
    <attr name="cam:LensID">(.*:)?[Ll]ensID|lens-id</attr>
    <attr name="cam:LensSpec">(.*:)?[Ll]ensSpec|lens-spec</attr>
    <attr name="cam:Make">(.*:)?Make|manufacturer</attr>
    <attr name="descr:Comment">(.*:)?[Cc]omment</attr>
    <attr name="descr:Keywords">(.*:)?[Kk]eywords</attr>
    <attr name="descr:Resource">(.*:)?[Rr]esource</attr>
    <attr name="descr:Subject">(.*:)?[Ss]ubject</attr>
    <attr name="descr:Subtitle">(.*:)?[Ss]ub[Tt]itle</attr>
    <attr name="descr:Title">(.*:)?[Tt]itle</attr>
    <attr name="descr:UserComment">(.*:)?UserComment|user-comment</attr>
    <attr name="exif:Aperture">(.*:)?Aperture</attr>
    <attr name="exif:ColorSpaceData">(.*:)?ColorSpaceData|color-space</attr>
    <attr name="exif:Contrast">(.*:)?[Cc]ontrast</attr>
    <attr name="exif:CreateDate">(.*:)?CreateDate|date-and-time</attr>
    <attr name="exif:DateTimeOriginal">(.*:)?DateTimeOriginal|date-and-time-original</attr>
    <attr name="exif:DepthOfField">(.*:)?[Dd]epth[oO]f[Ff]ield|depth-of-field</attr>
    <attr name="exif:ExposureCompensation">(.*:)?ExposureCompensation|exposure-bias|exposure-compensation</attr>
    <attr name="exif:ExposureMode">(.*:)?ExposureMode|exposure-mode</attr>
    <attr name="exif:ExposureProgram">(.*:)?ExposureProgram|exposure-program</attr>
    <attr name="exif:ExposureTime">(.*:)?ExposureTime|exposure-time</attr>
    <attr name="exif:Flash">(.*:)?[Ff]lash</attr>
    <attr name="exif:FlashSetting">(.*:)?[Ff]lash-?[Ss]etting</attr>
    <attr name="exif:FNumber">(.*:)?FNumber|fnumber</attr>
    <attr name="exif:FocalLength">(.*:)?FocalLength|focal-length</attr>
    <attr name="exif:FocalLengthIn35mmFormat">(.*:)?FocalLengthIn35mmFormat|focal-length-in-35mm</attr>
    <attr name="exif:FocusDistance">(.*:)?FocusDistance|focus-distance</attr>
    <attr name="exif:FocusMode">(.*:)?FocusMode|focus-mode</attr>
    <attr name="exif:ImageSize">(.*:)?ImageSize|geometry</attr>
    <attr name="exif:ISO">(.*:)?ISO|iso-setting</attr>
    <attr name="exif:MeteringMode">(.*:)?MeteringMode|metering-mode</attr>
    <attr name="exif:Quality">(.*:)?[Qq]uality</attr>
    <attr name="exif:Saturation">(.*:)?[Ss]aturation</attr>
    <attr name="exif:Sharpness">(.*:)?[Ss]harpness</attr>
    <attr name="exif:ShootingMode">(.*:)?ShootingMode|shooting-mode</attr>
    <attr name="exif:ShutterSpeed">(.*:)?ShutterSpeed|shutter-speed</attr>
    <attr name="exif:VibrationReduction">(.*:)?VibrationReduction|vibration-reduction</attr>
    <attr name="exif:WhiteBalance">(.*:)?WhiteBalance|white-balance</attr>
    <attr name="file:FileModificationDateTime">(.*:)?FileModificationDateTime|modified</attr>
    <attr name="file:FileSize">(.*:)?FileSize|file-size</attr>
    <attr name="file:RefOrig">(.*:)?RefOrig|ref-org</attr>
    <attr name="file:RefRaw">(.*:)?RefRaw|ref-raw</attr>
    <attr name="file:RefXmp">(.*:)?RefXmp|ref-xmp</attr>
    <attr name="show:Duration">(.*:)?[Dd]uration</attr>
  </picture-attributes>
  <layout id="html-1024x768" type="html-css2">
    <page type="album">
      <attr name="template">config/html-1024x768-album-template.xml</attr>
    </page>
    <page type="picture">
      <attr name="template">config/html-1024x768-picture-template.xml</attr>
    </page>
  </layout>
  <layout id="html-1600x1200" type="html-css2">
    <page type="album">
      <attr name="template">config/html-1600x1200-album-template.xml</attr>
    </page>
    <page type="picture">
      <attr name="template">config/html-1600x1200-picture-template.xml</attr>
    </page>
  </layout>
  <size>
    <attr name="dir">1600x1200</attr>
    <attr name="geometry">1600x1200</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">1024x768</attr>
    <attr name="geometry">1024x768</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">160x120</attr>
    <attr name="geometry">160x120</attr>
    <attr name="aspect-ratio">fix</attr>
  </size>
  <size>
    <attr name="dir">100x75</attr>
    <attr name="geometry">100x75</attr>
    <attr name="aspect-ratio">fix</attr>
  </size>
  <size>
    <attr name="dir">100x100</attr>
    <attr name="geometry">100x100</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
</config>
