=== UweSchmidt/apps/test/config/archive.dtd
<?xml encoding="ISO-8859-1"?>
<!-- DTD for a simple web photo album -->

<!-- the root tag -->
<!ELEMENT archive	(config?, album)	>
<!ATTLIST archive	xmlns	CDATA	#FIXED	"http://muehle.welt.all/photos.dtd"
			base	CDATA	#IMPLIED
			config	CDATA	#IMPLIED	>

<!-- general info for various tags for a arbitrary key-value pairs -->
<!ELEMENT attr		ANY				>
<!ATTLIST attr		name	CDATA	#REQUIRED
			entity	CDATA  	#IMPLIED	>

<!-- a collection of pictures and sub albums -->
<!ELEMENT album		(error*, orig?, copy*, attr*, (album | picture)*)	>
<!ATTLIST album		id	NMTOKEN	#REQUIRED
			entity	CDATA  	#IMPLIED
			extern	NMTOKEN	#IMPLIED
			base	CDATA	#IMPLIED
			baseref	CDATA	#IMPLIED
			href	CDATA	#IMPLIED	>

<!-- description of a single picture -->
<!ELEMENT picture	(error*, orig?, copy*, attr*)	>
<!ATTLIST picture	id	NMTOKEN	#REQUIRED
			entity	CDATA  	#IMPLIED
			base	CDATA	#IMPLIED
			baseref	CDATA	#IMPLIED
			href	CDATA	#IMPLIED	>

<!-- the original source of pictures -->
<!ELEMENT orig		EMPTY				>
<!ATTLIST orig		href	CDATA	#IMPLIED
			raw	CDATA	#IMPLIED
			href1	CDATA	#IMPLIED
			raw1	CDATA	#IMPLIED
			rotate	CDATA	#IMPLIED
			gamma	CDATA	#IMPLIED	>

<!-- the data about a resized copy of a picture -->
<!ELEMENT copy		EMPTY				>
<!ATTLIST copy		href	CDATA	#IMPLIED
			base	CDATA	#IMPLIED
			geometry CDATA	#IMPLIED	>

<!-- error messages when processing image or file -->
<!ELEMENT error		ANY				>

<!-- representation configuration data -->
<!ELEMENT config	(attr*, picture-attributes?, layout*, dictionary*, size*)		>
<!ATTLIST config	entity	CDATA  	#IMPLIED
			config	CDATA	#IMPLIED	>

<!ELEMENT picture-attributes	(attr*)			>

<!-- layout information about a specific layout -->
<!ELEMENT layout	(attr*, page*)			>
<!ATTLIST layout	id	NMTOKEN	#REQUIRED
			type	CDATA	#REQUIRED
			entity	CDATA  	#IMPLIED
			config	CDATA	#IMPLIED	>

<!-- dictionary for language translation layout -->
<!ELEMENT dictionary	(attr*)			>
<!ATTLIST dictionary	id	NMTOKEN	#REQUIRED	>

<!-- layout info about album or picture pages -->
<!ELEMENT page		(attr*)				>
<!ATTLIST page		type	( picture
				| album
				)	#REQUIRED
			entity	CDATA  	#IMPLIED
			config	CDATA	#IMPLIED	>

<!ELEMENT a		ANY				>
<!ATTLIST a		href	CDATA	#REQUIRED
                        title   CDATA   #IMPLIED
			target	CDATA  	#IMPLIED	>

<!-- size info for picture copies to be generated -->
<!ELEMENT size		(attr*)				>

<!-- include ISO Latin 1 xhtml entities -->
<!ENTITY % HTMLlat1 PUBLIC
       "-//W3C//ENTITIES Latin 1 for XHTML//EN"
       "xhtml-lat1.ent">
%HTMLlat1;

=== UweSchmidt/apps/photo2/test/album2/Hagenbeck/OrangUtang.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE album SYSTEM "../../config/archive.dtd">
<album id="OrangUtang">
  <orig href1="2007/2007.03.11.Hagenbeck/petra1/srgb/_dsc0053.jpg" raw1="2007/2007.03.11.Hagenbeck/petra1/_dsc0053.nef"/>
  <copy base="100x100" geometry="100x100"/>
  <copy base="100x75" geometry="100x75"/>
  <copy base="1024x768" geometry="1024x768"/>
  <copy base="1400x1050" geometry="1400x1050"/>
  <copy base="1600x1200" geometry="1600x1200"/>
  <copy base="160x120" geometry="160x120"/>
  <copy base="org" geometry="3024x2268"/>
  <attr name="cam:CameraModelName">NIKON D200</attr>
  <attr name="cam:FocalLength">400.0mm (35mm equivalent: 600.0mm)</attr>
  <attr name="cam:FocalLengthIn35mmFormat">600mm</attr>
  <attr name="cam:Lens">80-400mm f/4.5-5.6</attr>
  <attr name="cam:LensID">AF VR Zoom-Nikkor 80-400mm f/4.5-5.6D ED</attr>
  <attr name="cam:LensSpec">80-400mm f/4.5-5.6 D VR</attr>
  <attr name="cam:Make">NIKON CORPORATION</attr>
  <attr name="descr:Title">Im Orang Utang Haus</attr>
  <attr name="exif:Aperture">5.6</attr>
  <attr name="exif:ColorSpaceData">RGB</attr>
  <attr name="exif:Contrast">Normal</attr>
  <attr name="exif:CreateDate">2007-03-11 14:07:10</attr>
  <attr name="exif:DateTimeOriginal">2007-03-11 14:07:10.24</attr>
  <attr name="exif:ExposureCompensation">-1/3</attr>
  <attr name="exif:ExposureMode">Auto</attr>
  <attr name="exif:ExposureProgram">Program AE</attr>
  <attr name="exif:ExposureTime">1/180</attr>
  <attr name="exif:FNumber">5.6</attr>
  <attr name="exif:Flash">No Flash</attr>
  <attr name="exif:FlashSetting">Normal</attr>
  <attr name="exif:FocalLength">400.0mm</attr>
  <attr name="exif:FocalLengthIn35mmFormat">600</attr>
  <attr name="exif:FocusMode">AF-C</attr>
  <attr name="exif:ISO">800</attr>
  <attr name="exif:ImageSize">3024x2268</attr>
  <attr name="exif:MeteringMode">Multi-segment</attr>
  <attr name="exif:Quality">Raw</attr>
  <attr name="exif:Saturation">Normal</attr>
  <attr name="exif:Sharpness">Normal</attr>
  <attr name="exif:ShootingMode">Continuous</attr>
  <attr name="exif:ShutterSpeed">1/180</attr>
  <attr name="exif:WhiteBalance">Auto</attr>
  <attr name="file:FileModificationDateTime">2007-03-15 19:40:24</attr>
  <attr name="file:FileSize">4 MB</attr>
  <attr name="file:RefOrig">../Diakaesten/2007/2007.03.11.Hagenbeck/petra1/srgb/_dsc0053.jpg</attr>
  <attr name="file:RefRaw">../Diakaesten/2007/2007.03.11.Hagenbeck/petra1/_dsc0053.nef</attr>
  <picture id="pic-0001" href="album2/Hagenbeck/OrangUtang/pic-0001.xml"/>
  <picture id="pic-0002" href="album2/Hagenbeck/OrangUtang/pic-0002.xml"/>
  <picture id="pic-0003" href="album2/Hagenbeck/OrangUtang/pic-0003.xml"/>
  <picture id="pic-0004" href="album2/Hagenbeck/OrangUtang/pic-0004.xml"/>
  <picture id="pic-0005" href="album2/Hagenbeck/OrangUtang/pic-0005.xml"/>
  <picture id="pic-0006" href="album2/Hagenbeck/OrangUtang/pic-0006.xml"/>
  <picture id="pic-0007" href="album2/Hagenbeck/OrangUtang/pic-0007.xml"/>
  <picture id="pic-0008" href="album2/Hagenbeck/OrangUtang/pic-0008.xml"/>
  <picture id="pic-0009" href="album2/Hagenbeck/OrangUtang/pic-0009.xml"/>
  <picture id="pic-0010" href="album2/Hagenbeck/OrangUtang/pic-0010.xml"/>
  <picture id="pic-0011" href="album2/Hagenbeck/OrangUtang/pic-0011.xml"/>
  <picture id="pic-0012" href="album2/Hagenbeck/OrangUtang/pic-0012.xml"/>
  <picture id="pic-0013" href="album2/Hagenbeck/OrangUtang/pic-0013.xml"/>
  <picture id="pic-0014" href="album2/Hagenbeck/OrangUtang/pic-0014.xml"/>
  <picture id="pic-0015" href="album2/Hagenbeck/OrangUtang/pic-0015.xml"/>
  <picture id="pic-0016" href="album2/Hagenbeck/OrangUtang/pic-0016.xml"/>
  <picture id="pic-0017" href="album2/Hagenbeck/OrangUtang/pic-0017.xml"/>
  <picture id="pic-0018" href="album2/Hagenbeck/OrangUtang/pic-0018.xml"/>
  <picture id="pic-0019" href="album2/Hagenbeck/OrangUtang/pic-0019.xml"/>
  <picture id="pic-0020" href="album2/Hagenbeck/OrangUtang/pic-0020.xml"/>
  <picture id="pic-0021" href="album2/Hagenbeck/OrangUtang/pic-0021.xml"/>
  <picture id="pic-0022" href="album2/Hagenbeck/OrangUtang/pic-0022.xml"/>
  <picture id="pic-0023" href="album2/Hagenbeck/OrangUtang/pic-0023.xml"/>
  <picture id="pic-0024" href="album2/Hagenbeck/OrangUtang/pic-0024.xml"/>
  <picture id="pic-0025" href="album2/Hagenbeck/OrangUtang/pic-0025.xml"/>
  <picture id="pic-0026" href="album2/Hagenbeck/OrangUtang/pic-0026.xml"/>
  <picture id="pic-0027" href="album2/Hagenbeck/OrangUtang/pic-0027.xml"/>
  <picture id="pic-0028" href="album2/Hagenbeck/OrangUtang/pic-0028.xml"/>
  <picture id="pic-0029" href="album2/Hagenbeck/OrangUtang/pic-0029.xml"/>
  <picture id="pic-0030" href="album2/Hagenbeck/OrangUtang/pic-0030.xml"/>
  <picture id="pic-0031" href="album2/Hagenbeck/OrangUtang/pic-0031.xml"/>
  <picture id="pic-0032" href="album2/Hagenbeck/OrangUtang/pic-0032.xml"/>
  <picture id="pic-0033" href="album2/Hagenbeck/OrangUtang/pic-0033.xml"/>
  <picture id="pic-0034" href="album2/Hagenbeck/OrangUtang/pic-0034.xml"/>
  <picture id="pic-0035" href="album2/Hagenbeck/OrangUtang/pic-0035.xml"/>
  <picture id="pic-0036" href="album2/Hagenbeck/OrangUtang/pic-0036.xml"/>
  <picture id="pic-0037" href="album2/Hagenbeck/OrangUtang/pic-0037.xml"/>
  <picture id="pic-0038" href="album2/Hagenbeck/OrangUtang/pic-0038.xml"/>
  <picture id="pic-0039" href="album2/Hagenbeck/OrangUtang/pic-0039.xml"/>
  <picture id="pic-0040" href="album2/Hagenbeck/OrangUtang/pic-0040.xml"/>
  <picture id="pic-0041" href="album2/Hagenbeck/OrangUtang/pic-0041.xml"/>
  <picture id="pic-0042" href="album2/Hagenbeck/OrangUtang/pic-0042.xml"/>
  <picture id="pic-0043" href="album2/Hagenbeck/OrangUtang/pic-0043.xml"/>
  <picture id="pic-0044" href="album2/Hagenbeck/OrangUtang/pic-0044.xml"/>
  <picture id="pic-0045" href="album2/Hagenbeck/OrangUtang/pic-0045.xml"/>
  <picture id="pic-0046" href="album2/Hagenbeck/OrangUtang/pic-0046.xml"/>
  <picture id="pic-0047" href="album2/Hagenbeck/OrangUtang/pic-0047.xml"/>
  <picture id="pic-0048" href="album2/Hagenbeck/OrangUtang/pic-0048.xml"/>
  <picture id="pic-0049" href="album2/Hagenbeck/OrangUtang/pic-0049.xml"/>
  <picture id="pic-0050" href="album2/Hagenbeck/OrangUtang/pic-0050.xml"/>
  <picture id="pic-0051" href="album2/Hagenbeck/OrangUtang/pic-0051.xml"/>
  <picture id="pic-0052" href="album2/Hagenbeck/OrangUtang/pic-0052.xml"/>
  <picture id="pic-0053" href="album2/Hagenbeck/OrangUtang/pic-0053.xml"/>
  <picture id="pic-0054" href="album2/Hagenbeck/OrangUtang/pic-0054.xml"/>
  <picture id="pic-0055" href="album2/Hagenbeck/OrangUtang/pic-0055.xml"/>
  <picture id="pic-0056" href="album2/Hagenbeck/OrangUtang/pic-0056.xml"/>
  <picture id="pic-0057" href="album2/Hagenbeck/OrangUtang/pic-0057.xml"/>
  <picture id="pic-0058" href="album2/Hagenbeck/OrangUtang/pic-0058.xml"/>
  <picture id="pic-0059" href="album2/Hagenbeck/OrangUtang/pic-0059.xml"/>
  <picture id="pic-0060" href="album2/Hagenbeck/OrangUtang/pic-0060.xml"/>
  <picture id="pic-0061" href="album2/Hagenbeck/OrangUtang/pic-0061.xml"/>
  <picture id="pic-0062" href="album2/Hagenbeck/OrangUtang/pic-0062.xml"/>
  <picture id="pic-0063" href="album2/Hagenbeck/OrangUtang/pic-0063.xml"/>
  <picture id="pic-0064" href="album2/Hagenbeck/OrangUtang/pic-0064.xml"/>
  <picture id="pic-0065" href="album2/Hagenbeck/OrangUtang/pic-0065.xml"/>
  <picture id="pic-0066" href="album2/Hagenbeck/OrangUtang/pic-0066.xml"/>
  <picture id="pic-0067" href="album2/Hagenbeck/OrangUtang/pic-0067.xml"/>
  <picture id="pic-0068" href="album2/Hagenbeck/OrangUtang/pic-0068.xml"/>
</album>

=== UweSchmidt/apps/photo2/test/album2/Hagenbeck/Gefluegel/Pelikan/pic-0003.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE picture SYSTEM "../../../../config/archive.dtd">
<picture id="pic-0003">
  <orig href1="2007/2007.03.11.Hagenbeck/uwe1/srgb/_uwe0011.jpg" raw1="2007/2007.03.11.Hagenbeck/uwe1/_uwe0011.nef"/>
  <copy base="100x100" geometry="100x100"/>
  <copy base="100x75" geometry="100x75"/>
  <copy base="1024x768" geometry="1024x768"/>
  <copy base="1400x1050" geometry="1400x1050"/>
  <copy base="1600x1200" geometry="1600x1200"/>
  <copy base="160x120" geometry="160x120"/>
  <copy base="160x160" geometry="160x107"/>
  <copy base="org" geometry="3898x2613"/>
  <attr name="cam:CameraModelName">NIKON D200</attr>
  <attr name="cam:FocalLength">600.0mm (35mm equivalent: 900.0mm)</attr>
  <attr name="cam:FocalLengthIn35mmFormat">900mm</attr>
  <attr name="cam:Lens">300mm f/2.8</attr>
  <attr name="cam:LensID">AF-S VR Nikkor 300mm f/2.8G IF-ED</attr>
  <attr name="cam:LensSpec">300mm f/2.8 G VR</attr>
  <attr name="cam:Make">NIKON CORPORATION</attr>
  <attr name="descr:Title">Pelikan</attr>
  <attr name="exif:Aperture">14.0</attr>
  <attr name="exif:ColorSpaceData">RGB</attr>
  <attr name="exif:Contrast">Normal</attr>
  <attr name="exif:CreateDate">2007-03-11 13:39:44</attr>
  <attr name="exif:DateTimeOriginal">2007-03-11 13:39:44.78</attr>
  <attr name="exif:ExposureCompensation">-1/3</attr>
  <attr name="exif:ExposureMode">Auto</attr>
  <attr name="exif:ExposureProgram">Program AE</attr>
  <attr name="exif:ExposureTime">1/800</attr>
  <attr name="exif:FNumber">14.0</attr>
  <attr name="exif:Flash">No Flash</attr>
  <attr name="exif:FlashSetting">Normal</attr>
  <attr name="exif:FocalLength">600.0mm</attr>
  <attr name="exif:FocalLengthIn35mmFormat">900</attr>
  <attr name="exif:FocusMode">AF-C</attr>
  <attr name="exif:ISO">640</attr>
  <attr name="exif:ImageSize">3898x2613</attr>
  <attr name="exif:MeteringMode">Multi-segment</attr>
  <attr name="exif:Quality">Raw</attr>
  <attr name="exif:Saturation">Normal</attr>
  <attr name="exif:Sharpness">Normal</attr>
  <attr name="exif:ShootingMode">Continuous</attr>
  <attr name="exif:ShutterSpeed">1/800</attr>
  <attr name="exif:WhiteBalance">Auto</attr>
  <attr name="file:FileModificationDateTime">2007-03-15 17:47:58</attr>
  <attr name="file:FileSize">7 MB</attr>
  <attr name="file:RefOrig">../Diakaesten/2007/2007.03.11.Hagenbeck/uwe1/srgb/_uwe0011.jpg</attr>
  <attr name="file:RefRaw">../Diakaesten/2007/2007.03.11.Hagenbeck/uwe1/_uwe0011.nef</attr>
</picture>

=== UweSchmidt/apps/photo2/test/album2/Hagenbeck/Clipboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE album SYSTEM "../../config/archive.dtd">
<album id="Clipboard">
  <orig href1="2007/2007.03.11.Hagenbeck/petra3/srgb/_dsc0057.jpg" raw1="2007/2007.03.11.Hagenbeck/petra3/_dsc0057.nef"/>
  <copy base="100x100" geometry="100x74"/>
  <copy base="100x75" geometry="100x75"/>
  <copy base="1024x768" geometry="1024x767"/>
  <copy base="1400x1050" geometry="1400x1049"/>
  <copy base="1600x1200" geometry="1600x1199"/>
  <copy base="160x120" geometry="160x120"/>
  <copy base="160x120-photoEdit" geometry="160x119"/>
  <copy base="160x160" geometry="160x119"/>
  <copy base="org" geometry="3342x2506"/>
  <attr name="cam:CameraModelName">NIKON D200</attr>
  <attr name="cam:FocalLength">400.0 mm (35 mm equivalent: 600.0 mm)</attr>
  <attr name="cam:FocalLengthIn35mmFormat">600 mm</attr>
  <attr name="cam:Make">NIKON CORPORATION</attr>
  <attr name="descr:Comment">Album für die Zwischenablage und für den Import neuer Bilder</attr>
  <attr name="descr:Subtitle">Zwischenablage und Album für Importe</attr>
  <attr name="descr:Title">Neue Bilder</attr>
  <attr name="exif:Aperture">14.0</attr>
  <attr name="exif:ColorSpaceData">RGB</attr>
  <attr name="exif:Contrast">Normal</attr>
  <attr name="exif:CreateDate">2007-03-11 17:01:08</attr>
  <attr name="exif:DateTimeOriginal">2007-03-11 17:01:08.82</attr>
  <attr name="exif:ExposureCompensation">-1/3</attr>
  <attr name="exif:ExposureMode">Auto</attr>
  <attr name="exif:ExposureProgram">Program AE</attr>
  <attr name="exif:ExposureTime">1/750</attr>
  <attr name="exif:FNumber">14.0</attr>
  <attr name="exif:Flash">No Flash</attr>
  <attr name="exif:ISO">400</attr>
  <attr name="exif:ImageSize">3342x2506</attr>
  <attr name="exif:MeteringMode">Multi-segment</attr>
  <attr name="exif:Saturation">Normal</attr>
  <attr name="exif:Sharpness">Normal</attr>
  <attr name="exif:ShutterSpeed">1/750</attr>
  <attr name="exif:WhiteBalance">Auto</attr>
  <attr name="file:FileModificationDateTime">2007-03-15 21:48:10</attr>
  <attr name="file:FileSize">5 MB</attr>
  <attr name="file:RefOrig">../Diakaesten/2007/2007.03.11.Hagenbeck/petra3/srgb/_dsc0057.jpg</attr>
  <attr name="file:RefRaw">../Diakaesten/2007/2007.03.11.Hagenbeck/petra3/_dsc0057.nef</attr>
  <picture id="pic-0001" href="album2/Hagenbeck/Clipboard/pic-0001.xml"/>
  <picture id="pic-0003" href="album2/Hagenbeck/Clipboard/pic-0003.xml"/>
  <picture id="pic-0042" href="album2/Hagenbeck/Clipboard/pic-0042.xml"/>
  <picture id="pic-0043" href="album2/Hagenbeck/Clipboard/pic-0043.xml"/>
  <picture id="pic-0006" href="album2/Hagenbeck/Clipboard/pic-0006.xml"/>
  <picture id="pic-0004" href="album2/Hagenbeck/Clipboard/pic-0004.xml"/>
  <picture id="pic-0002" href="album2/Hagenbeck/Clipboard/pic-0002.xml"/>
  <picture id="pic-0005" href="album2/Hagenbeck/Clipboard/pic-0005.xml"/>
  <picture id="pic-0007" href="album2/Hagenbeck/Clipboard/pic-0007.xml"/>
  <picture id="pic-0008" href="album2/Hagenbeck/Clipboard/pic-0008.xml"/>
  <picture id="pic-0009" href="album2/Hagenbeck/Clipboard/pic-0009.xml"/>
  <picture id="pic-0010" href="album2/Hagenbeck/Clipboard/pic-0010.xml"/>
  <picture id="pic-0011" href="album2/Hagenbeck/Clipboard/pic-0011.xml"/>
  <picture id="pic-0012" href="album2/Hagenbeck/Clipboard/pic-0012.xml"/>
  <picture id="pic-0013" href="album2/Hagenbeck/Clipboard/pic-0013.xml"/>
  <picture id="pic-0014" href="album2/Hagenbeck/Clipboard/pic-0014.xml"/>
  <picture id="pic-0015" href="album2/Hagenbeck/Clipboard/pic-0015.xml"/>
  <picture id="pic-0016" href="album2/Hagenbeck/Clipboard/pic-0016.xml"/>
</album>

=== UweSchmidt/apps/photo2/test/album2/Hagenbeck.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE album SYSTEM "../config/archive.dtd">
<album id="Hagenbeck">
  <orig href1="2007/2007.03.11.Hagenbeck/petra1/srgb/_dsc0048.jpg" raw1="2007/2007.03.11.Hagenbeck/petra1/_dsc0048.nef"/>
  <copy base="100x100" geometry="100x75"/>
  <copy base="100x75" geometry="100x75"/>
  <copy base="1024x768" geometry="1024x768"/>
  <copy base="1400x1050" geometry="1400x1050"/>
  <copy base="1600x1200" geometry="1600x1200"/>
  <copy base="160x120" geometry="160x120"/>
  <copy base="org" geometry="3256x2442"/>
  <attr name="cam:CameraModelName">NIKON D200</attr>
  <attr name="cam:FocalLength">310.0mm (35mm equivalent: 465.0mm)</attr>
  <attr name="cam:FocalLengthIn35mmFormat">465mm</attr>
  <attr name="cam:Lens">80-400mm f/4.5-5.6</attr>
  <attr name="cam:LensID">AF VR Zoom-Nikkor 80-400mm f/4.5-5.6D ED</attr>
  <attr name="cam:LensSpec">80-400mm f/4.5-5.6 D VR</attr>
  <attr name="cam:Make">NIKON CORPORATION</attr>
  <attr name="descr:Resource">
    <a href="http://maps.google.com/maps?f=q&amp;hl=de&amp;q=Hagenbeckstra%C3%9Fe,+Stellingen+22527+Hamburg,+Hamburg,+Hamburg,+Deutschland&amp;layer=&amp;sll=53.589366,9.941325&amp;sspn=0.021831,0.067635&amp;ie=UTF8&amp;z=16&amp;ll=53.596173,9.940567&amp;spn=0.010914,0.033817&amp;t=h&amp;om=1">google maps</a>
  </attr>
  <attr name="descr:Subtitle">bei herrlichem Frühlingswetter einmal durch den Tierpark</attr>
  <attr name="descr:Title">11. März 2007: Geh'n wir mal zu Hagenbeck</attr>
  <attr name="exif:Aperture">5.3</attr>
  <attr name="exif:ColorSpaceData">RGB</attr>
  <attr name="exif:Contrast">Normal</attr>
  <attr name="exif:CreateDate">2007-03-11 14:03:28</attr>
  <attr name="exif:DateTimeOriginal">2007-03-11 14:03:28.49</attr>
  <attr name="exif:ExposureCompensation">-1/3</attr>
  <attr name="exif:ExposureMode">Auto</attr>
  <attr name="exif:ExposureProgram">Program AE</attr>
  <attr name="exif:ExposureTime">1/350</attr>
  <attr name="exif:FNumber">5.3</attr>
  <attr name="exif:Flash">No Flash</attr>
  <attr name="exif:FlashSetting">Normal</attr>
  <attr name="exif:FocalLength">310.0mm</attr>
  <attr name="exif:FocalLengthIn35mmFormat">465</attr>
  <attr name="exif:FocusMode">AF-C</attr>
  <attr name="exif:ISO">800</attr>
  <attr name="exif:ImageSize">3256x2442</attr>
  <attr name="exif:MeteringMode">Multi-segment</attr>
  <attr name="exif:Quality">Raw</attr>
  <attr name="exif:Saturation">Normal</attr>
  <attr name="exif:Sharpness">Normal</attr>
  <attr name="exif:ShootingMode">Continuous</attr>
  <attr name="exif:ShutterSpeed">1/350</attr>
  <attr name="exif:WhiteBalance">Auto</attr>
  <attr name="file:FileModificationDateTime">2007-03-15 19:38:10</attr>
  <attr name="file:FileSize">4 MB</attr>
  <attr name="file:RefOrig">../Diakaesten/2007/2007.03.11.Hagenbeck/petra1/srgb/_dsc0048.jpg</attr>
  <attr name="file:RefRaw">../Diakaesten/2007/2007.03.11.Hagenbeck/petra1/_dsc0048.nef</attr>
  <album id="QuerBeet" href="album2/Hagenbeck/QuerBeet.xml"/>
  <album id="Gefluegel" href="album2/Hagenbeck/Gefluegel.xml"/>
  <album id="OrangUtang" href="album2/Hagenbeck/OrangUtang.xml"/>
  <album id="Tiger" href="album2/Hagenbeck/Tiger.xml"/>
  <album id="PinguinEisbaerRobben" href="album2/Hagenbeck/PinguinEisbaerRobben.xml"/>
  <album id="Enten" href="album2/Hagenbeck/Enten.xml"/>
  <album id="Flamingos" href="album2/Hagenbeck/Flamingos.xml"/>
  <album id="Zebras" href="album2/Hagenbeck/Zebras.xml"/>
  <album id="pumas" href="album2/Hagenbeck/pumas.xml"/>
  <album id="Clipboard" href="album2/Hagenbeck/Clipboard.xml"/>
</album>

=== UweSchmidt/apps/test/config/archive.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE config SYSTEM "archive.dtd">
<config>
  <attr name="base">../Diakaesten</attr>
  <attr name="copy-exif">1</attr>
  <attr name="copy-org">0</attr>
  <attr name="create-copy">0</attr>
  <attr name="debug">1</attr>
  <attr name="dir">org</attr>
  <attr name="dtd">config/archive.dtd</attr>
  <attr name="entities">archive</attr>
  <attr name="imgtype">jpg</attr>
  <attr name="import-pattern">.*/uwe2/.*</attr>
  <attr name="import-since">2007</attr>
  <picture-attributes>
    <attr name="cam:CameraModelName">(.*:)?CameraModelName|model</attr>
    <attr name="cam:FocalLength">(.*:)?FocalLength</attr>
    <attr name="cam:FocalLengthIn35mmFormat">(.*:)?FocalLengthIn35mmFormat</attr>
    <attr name="cam:Lens">(.*:)?[Ll]ens</attr>
    <attr name="cam:LensID">(.*:)?[Ll]ensID|lens-id</attr>
    <attr name="cam:LensSpec">(.*:)?[Ll]ensSpec|lens-spec</attr>
    <attr name="cam:Make">(.*:)?Make|manufacturer</attr>
    <attr name="descr:Comment">(.*:)?[Cc]omment</attr>
    <attr name="descr:Keywords">(.*:)?[Kk]eywords</attr>
    <attr name="descr:Resource">(.*:)?[Rr]esource</attr>
    <attr name="descr:Subject">(.*:)?[Ss]ubject</attr>
    <attr name="descr:Subtitle">(.*:)?[Ss]ub[Tt]itle</attr>
    <attr name="descr:Title">(.*:)?[Tt]itle</attr>
    <attr name="descr:UserComment">(.*:)?UserComment|user-comment</attr>
    <attr name="exif:Aperture">(.*:)?Aperture</attr>
    <attr name="exif:ColorSpaceData">(.*:)?ColorSpaceData|color-space</attr>
    <attr name="exif:Contrast">(.*:)?[Cc]ontrast</attr>
    <attr name="exif:CreateDate">(.*:)?CreateDate|date-and-time</attr>
    <attr name="exif:DateTimeOriginal">(.*:)?DateTimeOriginal|date-and-time-original</attr>
    <attr name="exif:ExposureCompensation">(.*:)?ExposureCompensation|exposure-bias|exposure-compensation</attr>
    <attr name="exif:ExposureMode">(.*:)?ExposureMode|exposure-mode</attr>
    <attr name="exif:ExposureProgram">(.*:)?ExposureProgram|exposure-program</attr>
    <attr name="exif:ExposureTime">(.*:)?ExposureTime|exposure-time</attr>
    <attr name="exif:Flash">(.*:)?[Ff]lash</attr>
    <attr name="exif:FlashSetting">(.*:)?[Ff]lash-?[Ss]etting</attr>
    <attr name="exif:FNumber">(.*:)?FNumber|fnumber</attr>
    <attr name="exif:FocalLength">(.*:)?FocalLength|focal-length</attr>
    <attr name="exif:FocalLengthIn35mmFormat">(.*:)?FocalLengthIn35mmFormat|focal-length-in-35mm</attr>
    <attr name="exif:FocusDistance">(.*:)?FocusDistance|focus-distance</attr>
    <attr name="exif:FocusMode">(.*:)?FocusMode|focus-mode</attr>
    <attr name="exif:ImageSize">(.*:)?ImageSize|geometry</attr>
    <attr name="exif:ISO">(.*:)?ISO|iso-setting</attr>
    <attr name="exif:MeteringMode">(.*:)?MeteringMode|metering-mode</attr>
    <attr name="exif:Quality">(.*:)?[Qq]uality</attr>
    <attr name="exif:Saturation">(.*:)?[Ss]aturation</attr>
    <attr name="exif:Sharpness">(.*:)?[Ss]harpness</attr>
    <attr name="exif:ShootingMode">(.*:)?ShootingMode|shooting-mode</attr>
    <attr name="exif:ShutterSpeed">(.*:)?ShutterSpeed|shutter-speed</attr>
    <attr name="exif:VibrationReduction">(.*:)?VibrationReduction|vibration-reduction</attr>
    <attr name="exif:WhiteBalance">(.*:)?WhiteBalance|white-balance</attr>
    <attr name="file:FileModificationDateTime">(.*:)?FileModificationDateTime|modified</attr>
    <attr name="file:FileSize">(.*:)?FileSize|file-size</attr>
    <attr name="file:RefOrig">(.*:)?RefOrig|ref-org</attr>
    <attr name="file:RefRaw">(.*:)?RefRaw|ref-raw</attr>
    <attr name="file:RefXmp">(.*:)?RefXmp|ref-xmp</attr>
    <attr name="show:Duration">(.*:)?[Dd]uration</attr>
  </picture-attributes>
  <layout id="1024x768-css" type="html-css">
    <attr name="css-file">config/album-1024x768.css</attr>
    <attr name="dictionary">
      <attr name="title">Titel</attr>
      <attr name="subtitle">Untertitel</attr>
      <attr name="descr">Beschreibung</attr>
      <attr name="comment">Kommentar</attr>
      <attr name="resource">Weitere Infos</attr>
      <attr name="maps">Karten</attr>
      <attr name="photographer">Fotograf</attr>
      <attr name="author">Autor</attr>
      <attr name="designer">Designer</attr>
      <attr name="date-and-time">Datum</attr>
      <attr name="exposure-time">Belichtungszeit</attr>
      <attr name="fnumber">Blende</attr>
      <attr name="focal-length">Brennweite</attr>
      <attr name="focal-length-in-35mm">Brennweite in 35mm</attr>
      <attr name="exposure-program">Aufnahmebetriebsart</attr>
      <attr name="exposure-mode">Belichtung</attr>
      <attr name="exposure-bias">Belichtungskorrektur</attr>
      <attr name="metering-mode">Belichtungsmessung</attr>
      <attr name="iso-setting">ISO Empfindlichkeit</attr>
      <attr name="quality">Aufnamequalit‰t</attr>
      <attr name="color-space">Farbraum</attr>
      <attr name="lens">Objektiv</attr>
      <attr name="lens-id">Objektiv (Modell)</attr>
      <attr name="focus-mode">Scharfeinstellung</attr>
      <attr name="shooting-mode">Aufnahmemodus</attr>
      <attr name="white-balance">Weiﬂabgleich</attr>
      <attr name="flash">Blitz</attr>
      <attr name="flash-setting">Blitzeinstellung</attr>
      <attr name="focus-mode">Scharfeinstellung</attr>
      <attr name="white-balance">Weiﬂabgleich</attr>
      <attr name="model">Kamera</attr>
      <attr name="ref-org">Bilddatei</attr>
      <attr name="ref-raw">Bilddatei (raw)</attr>
      <attr name="geometry">Geometrie</attr>
      <attr name="file-size">Bildateigrˆﬂe</attr>
      <attr name="modified">Datum (Bilddatei)</attr>
      <attr name="af-d-or-af-s-lens">AF-D oder AF-S Objektiv</attr>
      <attr name="aperture-priority">Zeitautomatik</attr>
      <attr name="aperture-priority-ae">Blendenvorwahl</attr>
      <attr name="auto-exposure">Automatik</attr>
      <attr name="auto-white-balance">Automatischer Weiﬂabgleich</attr>
      <attr name="center-weighted-average">Mittenzentriertes gewichtetes Mittel</attr>
      <attr name="continuous">Serie</attr>
      <attr name="continuous-exposure-bracketing">Belichtungsreihe</attr>
      <attr name="fine">jpg (hoch)</attr>
      <attr name="fired-return-detected">Mit Blitz</attr>
      <attr name="flash-did-not-fire-auto-mode">Kein Blitz</attr>
      <attr name="flash-did-not-fire">Kein Blitz</attr>
      <attr name="full-auto">Voll automatisch</attr>
      <attr name="manual-exposure">Manuell</attr>
      <attr name="manual">Manuell</attr>
      <attr name="manual-white-balance">Manueller Weiﬂabgleich</attr>
      <attr name="multi-segment">Multi-Segment</attr>
      <attr name="no-flash">Kein Blitz</attr>
      <attr name="normal">Normal</attr>
      <attr name="off">Aus</attr>
      <attr name="normal-program">Multiprogrammautomatik</attr>
      <attr name="pattern">Matrixmessung</attr>
      <attr name="program-ae">Programm-Automatik</attr>
      <attr name="raw">raw</attr>
      <attr name="s-rgb">sRGB</attr>
      <attr name="single-frame">Einzelaufnahme</attr>
      <attr name="single-frame-exposure-bracketing">Einzelaufnahme, Belichtungsreihe</attr>
      <attr name="strobe-return-light-detected">Mit Blitzlicht</attr>
      <attr name="shutter-priority">Blendenautomatik</attr>
      <attr name="uncalibrated">Unkalibriert</attr>
    </attr>
    <attr name="duration">7000</attr>
    <attr name="geometry">1024x768</attr>
    <attr name="javascript-file">config/album.js</attr>
    <page type="album">
      <attr name="dir">100x75</attr>
      <attr name="dir2">100x75</attr>
      <attr name="geometry">100x75</attr>
      <attr name="geometry2">50x37</attr>
      <attr name="icons-per-row">9</attr>
      <attr name="template">config/album-template.xml</attr>
    </page>
    <page type="picture">
      <attr name="dir">1024x768</attr>
      <attr name="geometry">1024x768</attr>
      <attr name="template">config/picture-template.xml</attr>
    </page>
  </layout>
  <layout id="html-1024x768" type="html-css2">
    <attr name="duration">7000</attr>
    <attr name="geometry">1024x768</attr>
    <page type="album">
      <attr name="dir">100x75</attr>
      <attr name="dir2">100x75</attr>
      <attr name="geometry">100x75</attr>
      <attr name="geometry2">50x37</attr>
      <attr name="icons-per-row">9</attr>
      <attr name="template">config/template-album.xml</attr>
    </page>
    <page type="picture">
      <attr name="dir">1024x768</attr>
      <attr name="geometry">1024x768</attr>
      <attr name="template">config/template-picture.xml</attr>
    </page>
  </layout>
  <size>
    <attr name="dir">1600x1200</attr>
    <attr name="geometry">1600x1200</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">1024x768</attr>
    <attr name="geometry">1024x768</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
  <size>
    <attr name="dir">100x75</attr>
    <attr name="geometry">100x75</attr>
    <attr name="aspect-ratio">fix</attr>
  </size>
  <size>
    <attr name="dir">100x100</attr>
    <attr name="geometry">100x100</attr>
    <attr name="aspect-ratio">pad</attr>
  </size>
</config>
